# Generated by Django 4.1 on 2022-09-02 16:25

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='static/cv/')),
                ('picture', models.ImageField(upload_to='static/image/')),
                ('about', models.TextField(max_length=500)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('python', models.IntegerField()),
                ('django', models.IntegerField()),
                ('drf', models.IntegerField()),
                ('git', models.IntegerField()),
                ('database', models.IntegerField()),
                ('docker', models.IntegerField()),
                ('telegram', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('stackoverflow', models.CharField(max_length=100)),
                ('gitlab', models.CharField(max_length=100)),
                ('discord', models.CharField(max_length=100)),
                ('reddit', models.CharField(max_length=100)),
                ('quora', models.CharField(max_length=100)),
                ('leetcode', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Specifications',
                'verbose_name_plural': 'Specifications',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('specification', models.ForeignKey(on_delete=deletion.CASCADE, related_name='experiences', to='server.specification')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fromm', models.TextField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('specification', models.ForeignKey(on_delete=deletion.CASCADE, related_name='educations', to='server.specification')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
    ]
